# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/VisualStudioProjects/fast-trading-data-processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/VisualStudioProjects/fast-trading-data-processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/VisualStudioProjects/fast-trading-data-processor/CMakeFiles /mnt/d/VisualStudioProjects/fast-trading-data-processor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/VisualStudioProjects/fast-trading-data-processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fast-trading-data-processor

# Build rule for target.
fast-trading-data-processor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-trading-data-processor
.PHONY : fast-trading-data-processor

# fast build rule for target.
fast-trading-data-processor/fast:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/build
.PHONY : fast-trading-data-processor/fast

#=============================================================================
# Target rules for targets named fast-trading-data-processor-tests

# Build rule for target.
fast-trading-data-processor-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fast-trading-data-processor-tests
.PHONY : fast-trading-data-processor-tests

# fast build rule for target.
fast-trading-data-processor-tests/fast:
	$(MAKE) -f test/CMakeFiles/fast-trading-data-processor-tests.dir/build.make test/CMakeFiles/fast-trading-data-processor-tests.dir/build
.PHONY : fast-trading-data-processor-tests/fast

ComputeDaySummaryDynamicVisitor.o: ComputeDaySummaryDynamicVisitor.cpp.o

.PHONY : ComputeDaySummaryDynamicVisitor.o

# target to build an object file
ComputeDaySummaryDynamicVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryDynamicVisitor.cpp.o
.PHONY : ComputeDaySummaryDynamicVisitor.cpp.o

ComputeDaySummaryDynamicVisitor.i: ComputeDaySummaryDynamicVisitor.cpp.i

.PHONY : ComputeDaySummaryDynamicVisitor.i

# target to preprocess a source file
ComputeDaySummaryDynamicVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryDynamicVisitor.cpp.i
.PHONY : ComputeDaySummaryDynamicVisitor.cpp.i

ComputeDaySummaryDynamicVisitor.s: ComputeDaySummaryDynamicVisitor.cpp.s

.PHONY : ComputeDaySummaryDynamicVisitor.s

# target to generate assembly for a file
ComputeDaySummaryDynamicVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryDynamicVisitor.cpp.s
.PHONY : ComputeDaySummaryDynamicVisitor.cpp.s

ComputeDaySummaryStaticVisitor.o: ComputeDaySummaryStaticVisitor.cpp.o

.PHONY : ComputeDaySummaryStaticVisitor.o

# target to build an object file
ComputeDaySummaryStaticVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryStaticVisitor.cpp.o
.PHONY : ComputeDaySummaryStaticVisitor.cpp.o

ComputeDaySummaryStaticVisitor.i: ComputeDaySummaryStaticVisitor.cpp.i

.PHONY : ComputeDaySummaryStaticVisitor.i

# target to preprocess a source file
ComputeDaySummaryStaticVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryStaticVisitor.cpp.i
.PHONY : ComputeDaySummaryStaticVisitor.cpp.i

ComputeDaySummaryStaticVisitor.s: ComputeDaySummaryStaticVisitor.cpp.s

.PHONY : ComputeDaySummaryStaticVisitor.s

# target to generate assembly for a file
ComputeDaySummaryStaticVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/ComputeDaySummaryStaticVisitor.cpp.s
.PHONY : ComputeDaySummaryStaticVisitor.cpp.s

LoadTradingDataDynamicVisitor.o: LoadTradingDataDynamicVisitor.cpp.o

.PHONY : LoadTradingDataDynamicVisitor.o

# target to build an object file
LoadTradingDataDynamicVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataDynamicVisitor.cpp.o
.PHONY : LoadTradingDataDynamicVisitor.cpp.o

LoadTradingDataDynamicVisitor.i: LoadTradingDataDynamicVisitor.cpp.i

.PHONY : LoadTradingDataDynamicVisitor.i

# target to preprocess a source file
LoadTradingDataDynamicVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataDynamicVisitor.cpp.i
.PHONY : LoadTradingDataDynamicVisitor.cpp.i

LoadTradingDataDynamicVisitor.s: LoadTradingDataDynamicVisitor.cpp.s

.PHONY : LoadTradingDataDynamicVisitor.s

# target to generate assembly for a file
LoadTradingDataDynamicVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataDynamicVisitor.cpp.s
.PHONY : LoadTradingDataDynamicVisitor.cpp.s

LoadTradingDataStaticVisitor.o: LoadTradingDataStaticVisitor.cpp.o

.PHONY : LoadTradingDataStaticVisitor.o

# target to build an object file
LoadTradingDataStaticVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataStaticVisitor.cpp.o
.PHONY : LoadTradingDataStaticVisitor.cpp.o

LoadTradingDataStaticVisitor.i: LoadTradingDataStaticVisitor.cpp.i

.PHONY : LoadTradingDataStaticVisitor.i

# target to preprocess a source file
LoadTradingDataStaticVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataStaticVisitor.cpp.i
.PHONY : LoadTradingDataStaticVisitor.cpp.i

LoadTradingDataStaticVisitor.s: LoadTradingDataStaticVisitor.cpp.s

.PHONY : LoadTradingDataStaticVisitor.s

# target to generate assembly for a file
LoadTradingDataStaticVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/LoadTradingDataStaticVisitor.cpp.s
.PHONY : LoadTradingDataStaticVisitor.cpp.s

SaveDaySummaryDynamicVisitor.o: SaveDaySummaryDynamicVisitor.cpp.o

.PHONY : SaveDaySummaryDynamicVisitor.o

# target to build an object file
SaveDaySummaryDynamicVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryDynamicVisitor.cpp.o
.PHONY : SaveDaySummaryDynamicVisitor.cpp.o

SaveDaySummaryDynamicVisitor.i: SaveDaySummaryDynamicVisitor.cpp.i

.PHONY : SaveDaySummaryDynamicVisitor.i

# target to preprocess a source file
SaveDaySummaryDynamicVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryDynamicVisitor.cpp.i
.PHONY : SaveDaySummaryDynamicVisitor.cpp.i

SaveDaySummaryDynamicVisitor.s: SaveDaySummaryDynamicVisitor.cpp.s

.PHONY : SaveDaySummaryDynamicVisitor.s

# target to generate assembly for a file
SaveDaySummaryDynamicVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryDynamicVisitor.cpp.s
.PHONY : SaveDaySummaryDynamicVisitor.cpp.s

SaveDaySummaryStaticVisitor.o: SaveDaySummaryStaticVisitor.cpp.o

.PHONY : SaveDaySummaryStaticVisitor.o

# target to build an object file
SaveDaySummaryStaticVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryStaticVisitor.cpp.o
.PHONY : SaveDaySummaryStaticVisitor.cpp.o

SaveDaySummaryStaticVisitor.i: SaveDaySummaryStaticVisitor.cpp.i

.PHONY : SaveDaySummaryStaticVisitor.i

# target to preprocess a source file
SaveDaySummaryStaticVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryStaticVisitor.cpp.i
.PHONY : SaveDaySummaryStaticVisitor.cpp.i

SaveDaySummaryStaticVisitor.s: SaveDaySummaryStaticVisitor.cpp.s

.PHONY : SaveDaySummaryStaticVisitor.s

# target to generate assembly for a file
SaveDaySummaryStaticVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/SaveDaySummaryStaticVisitor.cpp.s
.PHONY : SaveDaySummaryStaticVisitor.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fast-trading-data-processor.dir/build.make CMakeFiles/fast-trading-data-processor.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fast-trading-data-processor"
	@echo "... test"
	@echo "... fast-trading-data-processor-tests"
	@echo "... ComputeDaySummaryDynamicVisitor.o"
	@echo "... ComputeDaySummaryDynamicVisitor.i"
	@echo "... ComputeDaySummaryDynamicVisitor.s"
	@echo "... ComputeDaySummaryStaticVisitor.o"
	@echo "... ComputeDaySummaryStaticVisitor.i"
	@echo "... ComputeDaySummaryStaticVisitor.s"
	@echo "... LoadTradingDataDynamicVisitor.o"
	@echo "... LoadTradingDataDynamicVisitor.i"
	@echo "... LoadTradingDataDynamicVisitor.s"
	@echo "... LoadTradingDataStaticVisitor.o"
	@echo "... LoadTradingDataStaticVisitor.i"
	@echo "... LoadTradingDataStaticVisitor.s"
	@echo "... SaveDaySummaryDynamicVisitor.o"
	@echo "... SaveDaySummaryDynamicVisitor.i"
	@echo "... SaveDaySummaryDynamicVisitor.s"
	@echo "... SaveDaySummaryStaticVisitor.o"
	@echo "... SaveDaySummaryStaticVisitor.i"
	@echo "... SaveDaySummaryStaticVisitor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

